# Generated by Django 3.1.6 on 2025-11-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstuser',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=60)),
                ('emailid', models.CharField(max_length=45, unique=True)),
                ('pwd', models.CharField(max_length=13)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
    ]
