# Generated by Django 3.1.6 on 2025-11-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('coursedetail', models.CharField(max_length=100)),
                ('courseicon', models.CharField(max_length=60)),
            ],
        ),
    ]
