# Generated by Django 3.1.6 on 2025-11-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseproject', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('batchno', models.AutoField(primary_key=True, serialize=False)),
                ('batchtitle', models.CharField(max_length=20)),
                ('startdate', models.DateField()),
                ('facultyname', models.CharField(max_length=40)),
            ],
        ),
    ]
