# Generated by Django 3.1.6 on 2025-11-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseproject', '0003_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('admissionno', models.AutoField(primary_key=True, serialize=False)),
                ('batchno', models.IntegerField()),
                ('admissiondate', models.DateField()),
                ('emailid', models.CharField(max_length=45)),
            ],
        ),
    ]
